cache:
  directories:
    - ./node_modules
language: node_js
node_js:
  - "8"
script:
  - npm install
  - npm run test-coverage
  - node deploy.js $MNEMONIC $INFURA

after_success:
  - npm install codecov
  - codecov
